spring:
  application:
    name: activityservice
  data:
    mongodb:
      uri: mongodb://localhost:27017/
      database: activity_service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

Server:
  port: 8081

