spring:
  application:
    name: activityservice
  data:
    mongodb:
      uri: mongodb://localhost:27017/
      database: activity_service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/

Server:
  port: 8081

