spring:
  application:
    name: aiservice
  data:
    mongodb:
      uri: mongodb://localhost:27017/
      database: ai_service

eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
    instance:
      prefer-ip-address: true

Server:
    port: 8082